### ISSUE TITLE
Fails to build on Linux Mint 20.1 (hb.h: No such file or directory) - workaround included

### ISSUE THREAD

**Issue by TheOneWhoseUsernameWasTaken** [roccat-linux/roccat-tools#16]
Trying to compile the project according to INSTALL.TXT results in this error after running 'make':

```
[  0%] Building C object libroccathelper/CMakeFiles/libroccathelper.dir/gtk_roccat_helper.c.o
In file included from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from /usr/include/gtk-2.0/gdk/gdktypes.h:37,
                 from /usr/include/gtk-2.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from /home/mjw/Downloads/roccat-tools-master/libroccathelper/gtk_roccat_helper.h:21,
                 from /home/mjw/Downloads/roccat-tools-master/libroccathelper/gtk_roccat_helper.c:18:
/usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
      |          ^~~~~~
compilation terminated.
```

However, the file hb.h actually exists:

```
$ ls -l /usr/include/harfbuzz/hb.h 
-rw-r--r-- 1 root root 1490 Mär 31  2020 /usr/include/harfbuzz/hb.h
```

I can get around this by using this cmake command to set up the build directory:

```
CFLAGS='-isystem /usr/include/harfbuzz' cmake -DCMAKE_INSTALL_PREFIX="/usr" -DWITH_LUA=5.3 ..
```

Just for reference, this probably should be put somewhere in the build scripts.

**Comment by Ishidres** [comment]
Thanks for the workaround!
